import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:convert';

///import 'package:staffer/bloc/login_bloc/login_bloc.dart';
///
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as s;

Future<Autogenerated> timesheet() async {
  final s.FlutterSecureStorage storage = new s.FlutterSecureStorage();
  final String token = await storage.read(key: 'token');
  const url =
      'https://dev2.thestaffer.com/api/admin/employees/timesheet/list?customer=5&hours_for_week=2021/12/4&assignment_status_list=Active';
  print('dddddddddddddddddddd$token');
  String authorization = token;
  print('sssssssssssssssssssss$authorization');
  final response = await http.get(url, headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Authorization': 'Bearer $authorization'
  });
  print('Token : ${authorization}');

  print('aaaaaaaaaaaaaaaaaaaaaaaaa${response.statusCode}');
  if (response.statusCode == 200) {
    print('cccccccccccccccccccccccccccccccc${response.body}');
    var a = response.body;
    var b = jsonDecode(a);
    print(
        'ccccccccccvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvc${b['data']['records'][0]['time_sheet_daily'][0]['id']}');
    var c = b['data']['records'][0]['time_sheet_daily'][0];
    print('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnn$c');
    //print('vvvvvvvvvvvvvvvvvvv${jsonDecode(response.body)}');

    return Autogenerated.fromJson(jsonDecode(response.body));
  } else {
    print('vvvvvvvvvvvvvvvvvvv');
  }
}

class Autogenerated {
  Data data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  List<Records> records;

  Data({this.records});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['records'] != null) {
      records = <Records>[];
      json['records'].forEach((v) {
        records.add(new Records.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.records != null) {
      data['records'] = this.records.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Records {
  int employeeJobId;
  int employeeId;
  int customerId;
  String billingRate;
  String overtimeBillingRate;
  String payRate;
  String overtimePayRate;
  String empName;
  int jobNumber;
  String jobPosition;
  int timesheetTableId;
  TimeSheetWeekly timeSheetWeekly;
  List<TimeSheetDaily> timeSheetDaily;

  Records(
      {this.employeeJobId,
      this.employeeId,
      this.customerId,
      this.billingRate,
      this.overtimeBillingRate,
      this.payRate,
      this.overtimePayRate,
      this.empName,
      this.jobNumber,
      this.jobPosition,
      this.timesheetTableId,
      this.timeSheetWeekly,
      this.timeSheetDaily});

  Records.fromJson(Map<String, dynamic> json) {
    employeeJobId = json['employee_job_id'];
    employeeId = json['employee_id'];
    customerId = json['customer_id'];
    billingRate = json['billing_rate'];
    overtimeBillingRate = json['overtime_billing_rate'];
    payRate = json['pay_rate'];
    overtimePayRate = json['overtime_pay_rate'];
    empName = json['emp_name'];
    jobNumber = json['job_number'];
    jobPosition = json['job_position'];
    timesheetTableId = json['timesheet_table_id'];
    timeSheetWeekly = json['time_sheet_weekly'] != null
        ? new TimeSheetWeekly.fromJson(json['time_sheet_weekly'])
        : null;
    /* if (json['time_sheet_daily'] != null) {
      timeSheetDaily = <TimeSheetDaily>[];
      json['time_sheet_daily'].forEach((v) {
        timeSheetDaily.add(new TimeSheetDaily.fromJson(v));
      });
    }
    */
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['employee_job_id'] = this.employeeJobId;
    data['employee_id'] = this.employeeId;
    data['customer_id'] = this.customerId;
    data['billing_rate'] = this.billingRate;
    data['overtime_billing_rate'] = this.overtimeBillingRate;
    data['pay_rate'] = this.payRate;
    data['overtime_pay_rate'] = this.overtimePayRate;
    data['emp_name'] = this.empName;
    data['job_number'] = this.jobNumber;
    data['job_position'] = this.jobPosition;
    data['timesheet_table_id'] = this.timesheetTableId;
    if (this.timeSheetWeekly != null) {
      data['time_sheet_weekly'] = this.timeSheetWeekly.toJson();
    }
    /* if (this.timeSheetDaily != null) {
      data['time_sheet_daily'] =
          this.timeSheetDaily.map((v) => v.toJson()).toList();
    }*/
    return data;
  }
}

class TimeSheetWeekly {
  int id;
  int parentId;
  int employeeJobId;
  int customerId;
  int departmentId;
  int employeeId;
  String hoursForWeek;
  String createdAt;
  String updatedAt;
  Null invoiceId;
  int payrollStatus;
  Null ckDate;
  Null overtimeHours;
  Null regularHours;
  String timesheetType;

  TimeSheetWeekly(
      {this.id,
      this.parentId,
      this.employeeJobId,
      this.customerId,
      this.departmentId,
      this.employeeId,
      this.hoursForWeek,
      this.createdAt,
      this.updatedAt,
      this.invoiceId,
      this.payrollStatus,
      this.ckDate,
      this.overtimeHours,
      this.regularHours,
      this.timesheetType});

  TimeSheetWeekly.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    parentId = json['parent_id'];
    employeeJobId = json['employee_job_id'];
    customerId = json['customer_id'];
    departmentId = json['department_id'];
    employeeId = json['employee_id'];
    hoursForWeek = json['hours_for_week'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    invoiceId = json['invoice_id'];
    payrollStatus = json['payroll_status'];
    ckDate = json['ck_date'];
    overtimeHours = json['overtime_hours'];
    regularHours = json['regular_hours'];
    timesheetType = json['timesheet_type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['parent_id'] = this.parentId;
    data['employee_job_id'] = this.employeeJobId;
    data['customer_id'] = this.customerId;
    data['department_id'] = this.departmentId;
    data['employee_id'] = this.employeeId;
    data['hours_for_week'] = this.hoursForWeek;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['invoice_id'] = this.invoiceId;
    data['payroll_status'] = this.payrollStatus;
    data['ck_date'] = this.ckDate;
    data['overtime_hours'] = this.overtimeHours;
    data['regular_hours'] = this.regularHours;
    data['timesheet_type'] = this.timesheetType;
    return data;
  }
}

class TimeSheetDaily {
  int id;
  int employeeTimesheetWeeklyId;
  String rateType;
  Null startTime;
  Null endTime;
  String date;
  int overtimeHours;
  int regularHours;
  int billingRate;
  int overtimeBillingRate;
  int payRate;
  int overtimePayRate;
  Null deletedAt;
  String createdAt;
  String updatedAt;
  List<Null> timeSheetNotes;
  List<Null> timeSheetSpecialRate;
  List<Null> timeSheetHolidayRate;

  TimeSheetDaily(
      {this.id,
      this.employeeTimesheetWeeklyId,
      this.rateType,
      this.startTime,
      this.endTime,
      this.date,
      this.overtimeHours,
      this.regularHours,
      this.billingRate,
      this.overtimeBillingRate,
      this.payRate,
      this.overtimePayRate,
      this.deletedAt,
      this.createdAt,
      this.updatedAt,
      this.timeSheetNotes,
      this.timeSheetSpecialRate,
      this.timeSheetHolidayRate});

  TimeSheetDaily.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    employeeTimesheetWeeklyId = json['employee_timesheet_weekly_id'];
    rateType = json['rate_type'];
    startTime = json['start_time'];
    endTime = json['end_time'];
    date = json['date'];
    overtimeHours = json['overtime_hours'];
    regularHours = json['regular_hours'];
    billingRate = json['billing_rate'];
    overtimeBillingRate = json['overtime_billing_rate'];
    payRate = json['pay_rate'];
    overtimePayRate = json['overtime_pay_rate'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['time_sheet_notes'] != null) {
      timeSheetNotes = <Null>[];
      json['time_sheet_notes'].forEach((v) {
        //    timeSheetNotes.add(new Null.fromJson(v));
      });
    }
    if (json['time_sheet_special_rate'] != null) {
      timeSheetSpecialRate = <Null>[];
      json['time_sheet_special_rate'].forEach((v) {
        //     timeSheetSpecialRate.add(new Null.fromJson(v));
      });
    }
    if (json['time_sheet_holiday_rate'] != null) {
      timeSheetHolidayRate = <Null>[];
      json['time_sheet_holiday_rate'].forEach((v) {
        //  timeSheetHolidayRate.add(new Null.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['employee_timesheet_weekly_id'] = this.employeeTimesheetWeeklyId;
    data['rate_type'] = this.rateType;
    data['start_time'] = this.startTime;
    data['end_time'] = this.endTime;
    data['date'] = this.date;
    data['overtime_hours'] = this.overtimeHours;
    data['regular_hours'] = this.regularHours;
    data['billing_rate'] = this.billingRate;
    data['overtime_billing_rate'] = this.overtimeBillingRate;
    data['pay_rate'] = this.payRate;
    data['overtime_pay_rate'] = this.overtimePayRate;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.timeSheetNotes != null) {
      //  data['time_sheet_notes'] =   this.timeSheetNotes!.map((v) => v.toJson()).toList();
    }
    if (this.timeSheetSpecialRate != null) {
      ///   data['time_sheet_special_rate'] =  this.timeSheetSpecialRate!.map((v) => v.toJson()).toList();
    }
    if (this.timeSheetHolidayRate != null) {
      //  data['time_sheet_holiday_rate'] =   this.timeSheetHolidayRate!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TimeSheetApi extends StatefulWidget {
  @override
  _TimeSheetApiState createState() => _TimeSheetApiState();
}

class _TimeSheetApiState extends State<TimeSheetApi> {
  Future<Autogenerated> futureData;
  @override
  void initState() {
    super.initState();
    futureData = timesheet();
    print('aaaaaaaaaaaaaaaaaa$futureData');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          SizedBox(height: 15),
          Container(
            color: Colors.blueAccent,
            child: TextButton(
              child: Text("Button"),
              onPressed: () {
                timesheet();
              },
            ),
          ),
          FutureBuilder<Autogenerated>(
            future: futureData,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Column(
                  children: [
                    Text(
                        "employee_job_id   ==  ${snapshot.data.data.records[0].employeeJobId}"),
                    Text(
                        "employee_id   ==  ${snapshot.data.data.records[0].employeeId}"),
                    Text(
                        "customer_id   ==  ${snapshot.data.data.records[0].customerId}"),
                    Text(
                        "billing_rate   ==  ${snapshot.data.data.records[0].billingRate}"),
                    Text(
                        "overtime_billing_rate   ==  ${snapshot.data.data.records[0].overtimeBillingRate}"),
                    Text(
                        "Pay Rate   ==  ${snapshot.data.data.records[0].payRate}"),
                    Text(
                        "over_time pay rate   ==  ${snapshot.data.data.records[0]..overtimePayRate}"),
                    Text(
                        "emplyee name ==  ${snapshot.data.data.records[0].empName}"),
                    Text(
                        "Job number   ==  ${snapshot.data.data.records[0].jobNumber}"),
                    Text(
                        "Job Position   ==  ${snapshot.data.data.records[0].jobPosition}"),
                    Text(
                        "timesheet table id   ==  ${snapshot.data.data.records[0].timesheetTableId}"),
                    Text(
                        "-----------------------------------time_sheet_weekly----------------------"),
                    Text(
                        "id  == ${snapshot.data.data.records[0].timeSheetWeekly.id}"),
                    Text(
                        "parent id  == ${snapshot.data.data.records[0].timeSheetWeekly.parentId}"),
                    Text(
                        "employ job id  == ${snapshot.data.data.records[0].timeSheetWeekly.employeeJobId}"),
                    Text(
                        "customer id  == ${snapshot.data.data.records[0].timeSheetWeekly.customerId}"),
                    Text(
                        "department id  == ${snapshot.data.data.records[0].timeSheetWeekly.departmentId}"),
                    Text(
                        "employee id  == ${snapshot.data.data.records[0].timeSheetWeekly.employeeId}"),
                    Text(
                        "hours for week  == ${snapshot.data.data.records[0].timeSheetWeekly.hoursForWeek}"),
                    Text(
                        "created at  == ${snapshot.data.data.records[0].timeSheetWeekly.createdAt}"),
                    Text(
                        "updated  at  == ${snapshot.data.data.records[0].timeSheetWeekly.updatedAt}"),
                    Text(
                        "payroll  status  == ${snapshot.data.data.records[0].timeSheetWeekly.payrollStatus}"),
                    Text(
                        "week  type  == ${snapshot.data.data.records[0].timeSheetWeekly.timesheetType}"),
                  ],
                );
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              } else {
                print('jjjjjjjjj');
                return CircularProgressIndicator();
              }

              // By default, show a loading spinner.
            },
          ),
        ],
      ),
    );
  }
}
